### ISSUE TITLE
PermissionError: [Errno 13] Permission denied: 'assets/dashExtensions_default.js'

### ISSUE THREAD

**Issue by jwnelen** [thedirtyfew/dash-extensions#156]
Hi, I'm using dash-extensions for my dash app. I works locally but it does not work when deploying to production.

I'm trying to deploy to Google Cloud Run that uses a Docker file which partly i'll share as well.

I found this error and I'm not able to solve it. Is there someone here that might know a solution? I feels like it is not able to find this `dashExtensions_default.js` but this is in my assets folder locally... I also tried creating the assets folder my self, and then copying the file into this folder but this does not solve the error.

Stacktrace of the error
```
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/gunicorn/arbiter.py", line 589, in spawn_worker
    worker.init_process()
  File "/usr/local/lib/python3.10/site-packages/gunicorn/workers/gthread.py", line 92, in init_process
    super().init_process()
  File "/usr/local/lib/python3.10/site-packages/gunicorn/workers/base.py", line 134, in init_process
    self.load_wsgi()
  File "/usr/local/lib/python3.10/site-packages/gunicorn/workers/base.py", line 146, in load_wsgi
    self.wsgi = self.app.wsgi()
  File "/usr/local/lib/python3.10/site-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/usr/local/lib/python3.10/site-packages/gunicorn/app/wsgiapp.py", line 58, in load
    return self.load_wsgiapp()
  File "/usr/local/lib/python3.10/site-packages/gunicorn/app/wsgiapp.py", line 48, in load_wsgiapp
    return util.import_app(self.app_uri)
  File "/usr/local/lib/python3.10/site-packages/gunicorn/util.py", line 359, in import_app
    mod = importlib.import_module(module)
  File "/usr/local/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/dashboard/app.py", line 1, in <module>
    import dashboard.index as dashboard
  File "/dashboard/dashboard/index.py", line 11, in <module>
    from dashboard.layout.layout import page_dashboard, page_table, navbar
  File "/dashboard/dashboard/layout/layout.py", line 4, in <module>
    import dashboard.components.choropleth as choro
  File "/dashboard/dashboard/components/choropleth.py", line 7, in <module>
    import dashboard.layout.style_handler as style_handler
  File "/dashboard/dashboard/layout/style_handler.py", line 4, in <module>
    style_handle = assign("""function(feature, context){
  File "/usr/local/lib/python3.10/site-packages/dash_extensions/javascript.py", line 43, in assign
    _default_name_space.dump()
  File "/usr/local/lib/python3.10/site-packages/dash_extensions/javascript.py", line 37, in dump
    with open(os.path.join(assets_folder, "{}.js".format("_".join(self.args))), 'w') as f:
PermissionError: [Errno 13] Permission denied: 'assets/dashExtensions_default.js' 
```

Docker File
```
# Use the official lightweight Python image.
# https://hub.docker.com/_/python
FROM python:slim-buster

# Settings
# Allow statements and log messages to immediately appear in the Knative logs
ENV PYTHONUNBUFFERED True

# Create Working Directory
ENV APP_HOME /dashboard
ENV USER app
ADD . $APP_HOME
WORKDIR $APP_HOME

# Create venv
# RUN python -m venv venv

# Copy requirements.txt
COPY requirements.txt requirements.txt
RUN apt-get update

# Create User
RUN groupadd -r $USER && useradd -r -g $USER $USER

# create a folder called assets and chown it to the user and copy the assets
# folder to the assets folder
RUN mkdir -p $APP_HOME/assets
RUN chown -R $USER:$USER $APP_HOME/assets
COPY $APP_HOME/assets $APP_HOME/assets
```

**Comment by emilhe** [comment]
When the app runs, the dynamic assets (e.g. user defined functions) are written automatically to the assets folder. This error indicates that the Python script doesn't have write access to the folder.

**Comment by emilhe** [comment]
As it currently stands, I don't see a bug here. The behaviour seems to be intended (i.e. the error lies elsewhere, most likely in permission). Please reopen the issue if this is not the case.
