### ISSUE TITLE
ServersideOutput always returns None

### ISSUE THREAD

**Issue by slai-nick** [thedirtyfew/dash-extensions#204]
Hi,

Just trying dash_extensions and it looks promising, however I haven't been able to get `ServersideOutput` to run on my machine.
I was first trying on a personal example but couldn't get it to work when using it to store data, using the stored data as input always gave None.
So now I am also trying to runthe basic example from the doc but get the same issue.

```
import time
import plotly.express as px
from dash_extensions.enrich import DashProxy, Output, Input, State, ServersideOutput, html, dcc, \
    ServersideOutputTransform

app = DashProxy(transforms=[ServersideOutputTransform()])
app.layout = html.Div(
    [
        html.Button("Query data", id="btn"),
        dcc.Dropdown(id="dd"),
        dcc.Graph(id="graph"),
        dcc.Loading(dcc.Store(id="store"), fullscreen=True, type="dot"),
    ]
)

@app.callback(ServersideOutput("store", "data"), Input("btn", "n_clicks"), prevent_initial_call=True)
def query_data(n_clicks):
    time.sleep(3)  # emulate slow database operation
    return px.data.gapminder()  # no JSON serialization here

@app.callback(Output("dd", "options"),  Output("dd", "value"), Input("store", "data"), prevent_initial_call=True)
def update_dd(df):
    print(df)
    options = [{"label": column, "value": column} for column in df["year"]]   # no JSON de-serialization here
    return options, options[0]['value']

@app.callback(Output("graph", "figure"), [Input("dd", "value"), State("store", "data")], prevent_initial_call=True)
def update_graph(value, df):
    df = df.query("year == {}".format(value))  # no JSON de-serialization here
    return px.sunburst(df, path=["continent", "country"], values="pop", color="lifeExp", hover_data=["iso_alpha"])

if __name__ == "__main__":
    app.run_server()
``` 

The server output shows that `df` is `None` (after clicking the button) and also contains some http info:
```
Dash is running on http://127.0.0.1:8050/

 * Serving Flask app 'viewer'
 * Debug mode: off
WARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.
 * Running on http://127.0.0.1:8050
Press CTRL+C to quit
127.0.0.1 - - [25/Aug/2022 23:12:23] "GET / HTTP/1.1" 200 -
127.0.0.1 - - [25/Aug/2022 23:12:32] "GET / HTTP/1.1" 200 -
127.0.0.1 - - [25/Aug/2022 23:12:35] "GET / HTTP/1.1" 200 -
127.0.0.1 - - [25/Aug/2022 23:12:35] "GET /_dash-layout HTTP/1.1" 200 -
127.0.0.1 - - [25/Aug/2022 23:12:35] "GET /_dash-dependencies HTTP/1.1" 200 -
127.0.0.1 - - [25/Aug/2022 23:12:35] "GET /_dash-component-suites/dash/dcc/async-dropdown.js HTTP/1.1" 304 -
127.0.0.1 - - [25/Aug/2022 23:12:35] "GET /_dash-component-suites/dash/dcc/async-graph.js HTTP/1.1" 304 -
127.0.0.1 - - [25/Aug/2022 23:12:35] "GET /_dash-component-suites/dash/dcc/async-plotlyjs.js HTTP/1.1" 304 -
127.0.0.1 - - [25/Aug/2022 23:12:41] "POST /_dash-update-component HTTP/1.1" 200 -
None
[2022-08-25 23:12:41,707] ERROR in app: Exception on /_dash-update-component [POST]
Traceback (most recent call last):
  File "/opt/homebrew/Caskroom/miniforge/base/lib/python3.9/site-packages/flask/app.py", line 2525, in wsgi_app
    response = self.full_dispatch_request()
  File "/opt/homebrew/Caskroom/miniforge/base/lib/python3.9/site-packages/flask/app.py", line 1822, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/opt/homebrew/Caskroom/miniforge/base/lib/python3.9/site-packages/flask/app.py", line 1820, in full_dispatch_request
    rv = self.dispatch_request()
  File "/opt/homebrew/Caskroom/miniforge/base/lib/python3.9/site-packages/flask/app.py", line 1796, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/opt/homebrew/Caskroom/miniforge/base/lib/python3.9/site-packages/dash/dash.py", line 1259, in dispatch
    ctx.run(
  File "/opt/homebrew/Caskroom/miniforge/base/lib/python3.9/site-packages/dash/_callback.py", line 439, in add_context
    output_value = func(*func_args, **func_kwargs)  # %% callback invoked %%
  File "/opt/homebrew/Caskroom/miniforge/base/lib/python3.9/site-packages/dash_extensions/enrich.py", line 809, in decorated_function
    return f(*args)
  File "/Users/nicholasscottodiperto/work/viewer/src/tools/GraphViewer/viewer.py", line 24, in update_dd
    options = [{"label": column, "value": column} for column in df["year"]]   # no JSON de-serialization here
TypeError: 'NoneType' object is not subscriptable
```

**Comment by emilhe** [comment]
If looks like the cache is somehow not being populated properly. What versions are you using (OS, Python, dash-extensions)?

**Comment by slai-nick** [comment]
- Mac Os Montery
- python 3.9.13
- dash_extensions 0.0.71 (installed with conda)

**Comment by emilhe** [comment]
Ah, it's because you installed with Conda. Please try with pip, then you should get 0.1.5

**Comment by slai-nick** [comment]
Awesome, it works now!
Sorry for the dumb issue
