### ISSUE TITLE
Multi-threading: the no-output enhancement does not work when running Dash with Gunicorn

### ISSUE THREAD

**Issue by frnhr** [thedirtyfew/dash-extensions#80]
I'm running the official [callback_no_output.py](https://github.com/thedirtyfew/dash-extensions/blob/master/examples/callback_no_ouput.py) example. 

First thing, installing gunicorn: `pip install gunicorn`

Then, the only thing need to change in the example file is adding this line:

``` python
server = app.server
```

Run with gunicorn:
``` bash
gunicorn examples.callback_no_ouput:server
```

By default, gunicorn runs with one worker, and the example works fine.

----

However, when running with more then one worker, the example doesn't work:

``` bash
gunicorn --workers=2 examples.callback_no_ouput:server
```

The server runs, the page shows the button as expected, but clicking the buttons does nothing.

### Python error:

```
Exception on /_dash-update-component [POST]
Traceback (most recent call last):
  File "/Users/fran/.pyenv/versions/3.8.10/envs/dash-extensions/lib/python3.8/site-packages/dash/dash.py", line 1072, in dispatch
    func = self.callback_map[output]["callback"]
KeyError: '0cd4dea8-0137-4c83-b039-33fe63b48634.children'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/fran/.pyenv/versions/3.8.10/envs/dash-extensions/lib/python3.8/site-packages/flask/app.py", line 2070, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/fran/.pyenv/versions/3.8.10/envs/dash-extensions/lib/python3.8/site-packages/flask/app.py", line 1515, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/fran/.pyenv/versions/3.8.10/envs/dash-extensions/lib/python3.8/site-packages/flask/app.py", line 1513, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/fran/.pyenv/versions/3.8.10/envs/dash-extensions/lib/python3.8/site-packages/flask/app.py", line 1499, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/Users/fran/.pyenv/versions/3.8.10/envs/dash-extensions/lib/python3.8/site-packages/dash/dash.py", line 1075, in dispatch
    raise KeyError(msg.format(output))
KeyError: "Callback function not found for output '0cd4dea8-0137-4c83-b039-33fe63b48634.children', perhaps you forgot to prepend the '@'?"

```

### Browser error:

```
dash_renderer.v1_8_3m1604000091.min.js:20 TypeError: Cannot read property 'children' of undefined
    at Li (dash_renderer.v1_8_3m1604000091.min.js:20)
    at dash_renderer.v1_8_3m1604000091.min.js:20
    at new Promise (<anonymous>)
    at qi (dash_renderer.v1_8_3m1604000091.min.js:20)
    at dash_renderer.v1_8_3m1604000091.min.js:20
    at ot (dash_renderer.v1_8_3m1604000091.min.js:20)
    at dash_renderer.v1_8_3m1604000091.min.js:20
    at dash_renderer.v1_8_3m1604000091.min.js:20
    at t (dash_renderer.v1_8_3m1604000091.min.js:20)
    at dash_renderer.v1_8_3m1604000091.min.js:20
```

**Comment by emilhe** [comment]
The fix should be available in the latest release,

https://pypi.org/project/dash-extensions/0.0.56/
