### ISSUE TITLE
How to get websocket to run on google compute engine VM

### ISSUE THREAD

**Issue by ishi-xibo** [thedirtyfew/dash-extensions#89]
hi Emil - getting this Bad Request error when deploying to the VM. The port is set to 8050 in main.py. Is there a port number that needs to be whitelisted? 

gunicorn -t 0 -b 0.0.0.0:8050 main:server
[2021-06-29 10:28:56 +0000] [18103] [INFO] Starting gunicorn 20.1.0
[2021-06-29 10:28:56 +0000] [18103] [INFO] Listening at: http://0.0.0.0:8050 (18103)
[2021-06-29 10:28:56 +0000] [18103] [INFO] Using worker: sync
[2021-06-29 10:28:56 +0000] [18106] [INFO] Booting worker with pid: 18106
bank listing fn  vault-bank-file-button
Expecting value: line 1 column 1 (char 0)
no comments in file
apply_rules_bank fn id:  none
show_statement_graph fn
[2021-06-29 10:29:34 +0000] [18106] [ERROR] Error handling request /ws
Traceback (most recent call last):
  File "/home/ishi/ops-tool/venv/lib/python3.7/site-packages/gunicorn/workers/sync.py", line 136, in handle
    self.handle_request(listener, req, client, addr)
  File "/home/ishi/ops-tool/venv/lib/python3.7/site-packages/gunicorn/workers/sync.py", line 179, in handle_request
    respiter = self.wsgi(environ, resp.start_response)
  File "/home/ishi/ops-tool/venv/lib/python3.7/site-packages/flask/app.py", line 2464, in __call__
    return self.wsgi_app(environ, start_response)
  File "/home/ishi/ops-tool/venv/lib/python3.7/site-packages/flask_sockets.py", line 40, in __call__
    handler, values = adapter.match()
  File "/home/ishi/ops-tool/venv/lib/python3.7/site-packages/werkzeug/routing.py", line 2030, in match
    raise WebsocketMismatch()
werkzeug.routing.WebsocketMismatch: 400 Bad Request: The browser (or proxy) sent a request that this server could not understand.

**Comment by emilhe** [comment]
I haven't tried running the examples on GCE, so I would advise that you seek advice on using websockets with GCE.

**Comment by ishi-xibo** [comment]
Thank you for getting back to me. I tried with Google but they pointed me to using gunicorn with flask_sockets 
https://github.com/GoogleCloudPlatform/python-docs-samples/blob/master/appengine/flexible/websockets/app.yaml

dash doesn't like that it seems and I get a server crash. Do you recommend a production server other than gunicorn for deploying your implementation of websockets?

**Comment by ishi-xibo** [comment]
It turned out to be rather simple. Required Werkzeug==1.0.1 ahead of Flask in requirements.txt

and then runtime is gunicorn main:server -k flask_sockets.worker

**Comment by emiliobasualdo** [comment]
@ishi-xibo how does this solve the problem? Flask requires ` Werkzeug>=2.0`

`ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
flask 2.0.1 requires Werkzeug>=2.0, but you have werkzeug 1.0.1 which is incompatible.
`

I running `Werkzeug==2.0.1` and `"Flask==2.0.1"`
and getting the following error:
```
Dash is running on http://127.0.0.1:8080/

 * Serving Flask app 'app.apps.app' (lazy loading)
 * Environment: production
   WARNING: This is a development server. Do not use it in a production deployment.
   Use a production WSGI server instead.
 * Debug mode: on
Traceback (most recent call last):
  File "/home/pilo/dev/max-dashboard/venv/lib/python3.8/site-packages/flask/app.py", line 2088, in __call__
    return self.wsgi_app(environ, start_response)
  File "/home/pilo/dev/max-dashboard/venv/lib/python3.8/site-packages/flask_sockets.py", line 40, in __call__
    handler, values = adapter.match()
  File "/home/pilo/dev/max-dashboard/venv/lib/python3.8/site-packages/werkzeug/routing.py", line 2030, in match
    raise WebsocketMismatch()
werkzeug.routing.WebsocketMismatch: 400 Bad Request: The browser (or proxy) sent a request that this server could not understand.
```
when running the [websocket example](https://github.com/thedirtyfew/dash-extensions/blob/master/examples/websocket_update.py)

**Comment by ishi-xibo** [comment]
hi Emilio. I am using Werkzeug==1.0.1 with Flask 1.1.2.. That solved the problem.

Also note that, when using websockets, you have to set debug = False.. sockets doesn't like dash's debug mode
