### ISSUE TITLE
bug using State with ServersideOutput and memoize

### ISSUE THREAD

**Issue by ChengyuanSha** [thedirtyfew/dash-extensions#9]
Hi Emil, I think there is a bug using State with ServersideOutput and memoize. This does not appears in the previous version. I replicate this issue in the below example. Start by uploading any csv file. 

```python 
import base64
import datetime
import io
import pandas as pd
import dash_table
import dash_core_components as dcc
import dash_html_components as html
from dash_extensions.enrich import Dash, Output, State, Input, Trigger, ServersideOutput

app = Dash(prevent_initial_callbacks=True)
app.layout = html.Div([
    dcc.Upload(
        id='upload-data',
        children=html.Div([
            'Drag and Drop or ',
            html.A('Select Files')
        ]),
        style={
            'width': '100%',
            'height': '60px',
            'lineHeight': '60px',
            'borderWidth': '1px',
            'borderStyle': 'dashed',
            'borderRadius': '5px',
            'textAlign': 'center',
            'margin': '10px'
        },
        # Allow multiple files to be uploaded
        multiple=True
    ),
    dcc.Store(id='output-data-upload'),
])


def parse_contents(contents, filename, date):
    content_type, content_string = contents.split(',')

    decoded = base64.b64decode(content_string)
    try:
        if 'csv' in filename:
            # Assume that the user uploaded a CSV file
            df = pd.read_csv(
                io.StringIO(decoded.decode('utf-8')))
        elif 'xls' in filename:
            # Assume that the user uploaded an excel file
            df = pd.read_excel(io.BytesIO(decoded))
    except Exception as e:
        print(e)
        return html.Div([
            'There was an error processing this file.'
        ])

    return html.Div([
        html.H5(filename),
        html.H6(datetime.datetime.fromtimestamp(date)),

        dash_table.DataTable(
            data=df.to_dict('records'),
            columns=[{'name': i, 'id': i} for i in df.columns]
        ),

        html.Hr(),  # horizontal line

        # For debugging, display the raw contents provided by the web browser
        html.Div('Raw Content'),
        html.Pre(contents[0:200] + '...', style={
            'whiteSpace': 'pre-wrap',
            'wordBreak': 'break-all'
        })
    ])


@app.callback(ServersideOutput('output-data-upload', 'data'),
              [Input('upload-data', 'contents')],
              [State('upload-data', 'filename'),
               State('upload-data', 'last_modified')],
               memoize=True)
def update_output(list_of_contents, list_of_names, list_of_dates):
    if list_of_contents is not None:
        children = [
            parse_contents(c, n, d) for c, n, d in
            zip(list_of_contents, list_of_names, list_of_dates)]
        return children

if __name__ == '__main__':
    app.run_server(debug=True)

```

It throws:
```
IndexError: list index out of range

Traceback (most recent call last)
File "~~~~~\dash_extensions\enrich.py", line 339, in decorated_function
args = [arg for i, arg in enumerate(args) if i > len(callback[Input]) or
File "~~~~~~\dash_extensions\enrich.py", line 340, in <listcomp>
not isinstance(callback[Input][i], Trigger)]
IndexError: list index out of range
```

**Comment by emilhe** [comment]
Ah, yes, that seems like a bug. I just issued a fix in (0.0.27rc1).

**Comment by ChengyuanSha** [comment]
Thanks, it solves my issue!

**Comment by emilhe** [comment]
Great! I'll push a new non-rc release in the next days :)
